before:
  hooks:
    - go mod download
project_name: editorconfig-cli
release:
  github:
    owner: paulvollmer
    name: editorconfig-cli
builds:
  - env:
    - GO111MODULE=on
    - CGO_ENABLED=0
    main: ./cmd/editorconfig
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: editorconfig
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
